-- Casino seed data: US, European, Australian, Asian casinos
-- Delete old pre-existing entries (city_id was required before our schema change)
-- then insert curated seed list. Safe to re-run.
delete from public.casinos where city_id is not null;

-- US casinos
insert into public.casinos (name, source, city, state, country)
values
  ('Bellagio', 'seed', 'Las Vegas', 'Nevada', 'United States'),
  ('Caesars Palace', 'seed', 'Las Vegas', 'Nevada', 'United States'),
  ('MGM Grand', 'seed', 'Las Vegas', 'Nevada', 'United States'),
  ('The Venetian', 'seed', 'Las Vegas', 'Nevada', 'United States'),
  ('Wynn Las Vegas', 'seed', 'Las Vegas', 'Nevada', 'United States'),
  ('Encore at Wynn', 'seed', 'Las Vegas', 'Nevada', 'United States'),
  ('Aria Resort & Casino', 'seed', 'Las Vegas', 'Nevada', 'United States'),
  ('The Cosmopolitan', 'seed', 'Las Vegas', 'Nevada', 'United States'),
  ('Resorts World Las Vegas', 'seed', 'Las Vegas', 'Nevada', 'United States'),
  ('Planet Hollywood', 'seed', 'Las Vegas', 'Nevada', 'United States'),
  ('Flamingo Las Vegas', 'seed', 'Las Vegas', 'Nevada', 'United States'),
  ('Paris Las Vegas', 'seed', 'Las Vegas', 'Nevada', 'United States'),
  ('Treasure Island', 'seed', 'Las Vegas', 'Nevada', 'United States'),
  ('Circus Circus', 'seed', 'Las Vegas', 'Nevada', 'United States'),
  ('Golden Nugget', 'seed', 'Las Vegas', 'Nevada', 'United States'),
  ('The LINQ', 'seed', 'Las Vegas', 'Nevada', 'United States'),
  ('Park MGM', 'seed', 'Las Vegas', 'Nevada', 'United States'),
  ('New York-New York', 'seed', 'Las Vegas', 'Nevada', 'United States'),
  ('Excalibur', 'seed', 'Las Vegas', 'Nevada', 'United States'),
  ('Luxor', 'seed', 'Las Vegas', 'Nevada', 'United States'),
  ('Mandalay Bay', 'seed', 'Las Vegas', 'Nevada', 'United States'),
  ('WinStar World Casino', 'seed', 'Thackerville', 'Oklahoma', 'United States'),
  ('Hard Rock Casino', 'seed', 'Catoosa', 'Oklahoma', 'United States'),
  ('Choctaw Casino & Resort', 'seed', 'Durant', 'Oklahoma', 'United States'),
  ('Cherokee Casino', 'seed', 'West Siloam Springs', 'Oklahoma', 'United States'),
  ('Pechanga Resort Casino', 'seed', 'Temecula', 'California', 'United States'),
  ('Yaamava'' Resort & Casino', 'seed', 'Highland', 'California', 'United States'),
  ('Thunder Valley Casino Resort', 'seed', 'Lincoln', 'California', 'United States'),
  ('Morongo Casino Resort & Spa', 'seed', 'Cabazon', 'California', 'United States'),
  ('San Manuel Casino', 'seed', 'Highland', 'California', 'United States'),
  ('Foxwoods Resort Casino', 'seed', 'Mashantucket', 'Connecticut', 'United States'),
  ('Mohegan Sun', 'seed', 'Uncasville', 'Connecticut', 'United States'),
  ('Borgata Hotel Casino & Spa', 'seed', 'Atlantic City', 'New Jersey', 'United States'),
  ('Hard Rock Hotel & Casino', 'seed', 'Atlantic City', 'New Jersey', 'United States'),
  ('Ocean Casino Resort', 'seed', 'Atlantic City', 'New Jersey', 'United States'),
  ('Seminole Hard Rock Hotel & Casino', 'seed', 'Tampa', 'Florida', 'United States'),
  ('Beau Rivage Resort & Casino', 'seed', 'Biloxi', 'Mississippi', 'United States'),
  ('Parx Casino', 'seed', 'Bensalem', 'Pennsylvania', 'United States'),
  ('Wind Creek Bethlehem', 'seed', 'Bethlehem', 'Pennsylvania', 'United States'),
  ('Rivers Casino', 'seed', 'Philadelphia', 'Pennsylvania', 'United States'),
  ('MGM National Harbor', 'seed', 'Oxon Hill', 'Maryland', 'United States'),
  ('Live! Casino & Hotel', 'seed', 'Hanover', 'Maryland', 'United States'),
  ('Horseshoe Casino', 'seed', 'Hammond', 'Indiana', 'United States'),
  ('Ameristar Casino', 'seed', 'St. Charles', 'Missouri', 'United States'),
  ('Turning Stone Resort Casino', 'seed', 'Verona', 'New York', 'United States'),
  ('Riverwind Casino', 'seed', 'Norman', 'Oklahoma', 'United States'),
  ('Kickapoo Casino', 'seed', 'Shawnee', 'Oklahoma', 'United States'),
  ('Comanche Nation Casino', 'seed', 'Lawton', 'Oklahoma', 'United States'),
  ('Chickasaw Casino', 'seed', 'Ardmore', 'Oklahoma', 'United States'),
  ('Gold River Casino', 'seed', 'Pauls Valley', 'Oklahoma', 'United States'),
  ('7 Clans First Council Casino', 'seed', 'Newkirk', 'Oklahoma', 'United States'),
  ('Apache Casino Hotel', 'seed', 'Lawton', 'Oklahoma', 'United States'),
  ('Mystic Lake Casino', 'seed', 'Prior Lake', 'Minnesota', 'United States'),
  ('Canterbury Park', 'seed', 'Shakopee', 'Minnesota', 'United States'),
  ('Treasure Island Casino', 'seed', 'Red Wing', 'Minnesota', 'United States'),
  ('Jackpot Junction Casino', 'seed', 'Morton', 'Minnesota', 'United States'),
  ('Prairie Edge Casino', 'seed', 'Watertown', 'South Dakota', 'United States'),
  ('Deadwood Mountain Grand', 'seed', 'Deadwood', 'South Dakota', 'United States'),
  ('Four Bears Casino', 'seed', 'New Town', 'North Dakota', 'United States'),
  ('Spirit Lake Casino', 'seed', 'Fort Totten', 'North Dakota', 'United States'),
  ('Tulalip Resort Casino', 'seed', 'Marysville', 'Washington', 'United States'),
  ('Muckleshoot Casino Resort', 'seed', 'Auburn', 'Washington', 'United States'),
  ('Snoqualmie Casino', 'seed', 'Snoqualmie', 'Washington', 'United States'),
  ('Little Creek Casino Resort', 'seed', 'Shelton', 'Washington', 'United States'),
  ('Harrah''s Cherokee Casino Resort', 'seed', 'Cherokee', 'North Carolina', 'United States'),
  ('Coushatta Casino Resort', 'seed', 'Kinder', 'Louisiana', 'United States'),
  ('L''Auberge Casino Resort', 'seed', 'Lake Charles', 'Louisiana', 'United States'),
  ('Margaritaville Resort Casino', 'seed', 'Bossier City', 'Louisiana', 'United States'),
  ('Delta Downs Casino', 'seed', 'Vinton', 'Louisiana', 'United States'),
  ('Soaring Eagle Casino & Resort', 'seed', 'Mount Pleasant', 'Michigan', 'United States'),
  ('FireKeepers Casino', 'seed', 'Battle Creek', 'Michigan', 'United States'),
  ('Gun Lake Casino', 'seed', 'Wayland', 'Michigan', 'United States'),
  ('Potawatomi Casino Hotel', 'seed', 'Milwaukee', 'Wisconsin', 'United States'),
  ('Ho-Chunk Casino', 'seed', 'Baraboo', 'Wisconsin', 'United States'),
  ('Oneida Casino', 'seed', 'Green Bay', 'Wisconsin', 'United States'),
  ('Isle Casino Waterloo', 'seed', 'Waterloo', 'Iowa', 'United States'),
  ('Horseshoe Council Bluffs', 'seed', 'Council Bluffs', 'Iowa', 'United States'),
  ('Argosy Casino', 'seed', 'Alton', 'Illinois', 'United States'),
  ('Hollywood Casino', 'seed', 'Aurora', 'Illinois', 'United States'),
  ('Blue Chip Casino', 'seed', 'Michigan City', 'Indiana', 'United States'),
  ('Belterra Casino', 'seed', 'Belterra', 'Indiana', 'United States'),
  ('French Lick Resort', 'seed', 'French Lick', 'Indiana', 'United States'),
  ('Rising Sun Casino', 'seed', 'Rising Sun', 'Indiana', 'United States'),
  ('Mountaineer Casino', 'seed', 'New Cumberland', 'West Virginia', 'United States'),
  ('Jack Cleveland Casino', 'seed', 'Cleveland', 'Ohio', 'United States'),
  ('MGM Northfield Park', 'seed', 'Northfield', 'Ohio', 'United States'),
  ('Presque Isle Downs & Casino', 'seed', 'Erie', 'Pennsylvania', 'United States'),
  ('Harrah''s Philadelphia', 'seed', 'Chester', 'Pennsylvania', 'United States'),
  ('Live! Casino Pittsburgh', 'seed', 'Washington', 'Pennsylvania', 'United States'),
  ('Ocean Downs Casino', 'seed', 'Berlin', 'Maryland', 'United States'),
  ('Wind Creek Atmore', 'seed', 'Atmore', 'Alabama', 'United States'),
  ('Wind Creek Montgomery', 'seed', 'Montgomery', 'Alabama', 'United States'),
  ('Agua Caliente Casino', 'seed', 'Rancho Mirage', 'California', 'United States'),
  ('Talking Stick Resort', 'seed', 'Scottsdale', 'Arizona', 'United States'),
  ('Casino Arizona', 'seed', 'Scottsdale', 'Arizona', 'United States'),
  ('Harrah''s Ak-Chin Casino', 'seed', 'Maricopa', 'Arizona', 'United States'),
  ('Desert Diamond Casino', 'seed', 'Tucson', 'Arizona', 'United States'),
  ('Casino Del Sol', 'seed', 'Tucson', 'Arizona', 'United States'),
  ('Barona Resort & Casino', 'seed', 'Lakeside', 'California', 'United States'),
  ('Viejas Casino', 'seed', 'Alpine', 'California', 'United States'),
  ('Jamul Casino', 'seed', 'Jamul', 'California', 'United States'),
  ('Sycuan Casino Resort', 'seed', 'El Cajon', 'California', 'United States'),
  ('Pala Casino Spa Resort', 'seed', 'Pala', 'California', 'United States')
on conflict (lower(name)) do nothing;

-- European casinos
insert into public.casinos (name, source, city, state, country)
values
  ('Casino de Monte-Carlo', 'seed', 'Monte Carlo', '', 'Monaco'),
  ('Grand Casino de Monte-Carlo', 'seed', 'Monte Carlo', '', 'Monaco'),
  ('Casino Baden-Baden', 'seed', 'Baden-Baden', '', 'Germany'),
  ('Casino Wiesbaden', 'seed', 'Wiesbaden', '', 'Germany'),
  ('Casino Hohensyburg', 'seed', 'Dortmund', '', 'Germany'),
  ('Spielbank Berlin', 'seed', 'Berlin', '', 'Germany'),
  ('Spielbank Hamburg', 'seed', 'Hamburg', '', 'Germany'),
  ('Casino Estoril', 'seed', 'Estoril', '', 'Portugal'),
  ('Casino Lisboa', 'seed', 'Lisbon', '', 'Portugal'),
  ('Casino do Estoril', 'seed', 'Estoril', '', 'Portugal'),
  ('Casino de Marbella', 'seed', 'Marbella', '', 'Spain'),
  ('Casino de Barcelona', 'seed', 'Barcelona', '', 'Spain'),
  ('Gran Casino de Madrid', 'seed', 'Madrid', '', 'Spain'),
  ('Casino de Santander', 'seed', 'Santander', '', 'Spain'),
  ('Casino Campione', 'seed', 'Campione d''Italia', '', 'Italy'),
  ('Casino di Venezia', 'seed', 'Venice', '', 'Italy'),
  ('Casino di Sanremo', 'seed', 'Sanremo', '', 'Italy'),
  ('Casino di Saint-Vincent', 'seed', 'Saint-Vincent', '', 'Italy'),
  ('Casino de Deauville', 'seed', 'Deauville', '', 'France'),
  ('Casino Barrière Enghien-les-Bains', 'seed', 'Enghien-les-Bains', '', 'France'),
  ('Casino Barrière Deauville', 'seed', 'Deauville', '', 'France'),
  ('Empire Casino', 'seed', 'London', '', 'United Kingdom'),
  ('The Hippodrome Casino', 'seed', 'London', '', 'United Kingdom'),
  ('Aspers Casino', 'seed', 'London', '', 'United Kingdom'),
  ('Grosvenor Casino', 'seed', 'London', '', 'United Kingdom'),
  ('Casino Admiral', 'seed', 'Prague', '', 'Czech Republic'),
  ('Casino Corinthia', 'seed', 'Prague', '', 'Czech Republic'),
  ('Casino Royale', 'seed', 'Riga', '', 'Latvia'),
  ('Olympic Casino', 'seed', 'Tallinn', '', 'Estonia'),
  ('Casino Helsinki', 'seed', 'Helsinki', '', 'Finland'),
  ('Casino Cosmopol', 'seed', 'Stockholm', '', 'Sweden'),
  ('Grand Casino Liechtenstein', 'seed', 'Bendern', '', 'Liechtenstein'),
  ('Casino Kursaal Interlaken', 'seed', 'Interlaken', '', 'Switzerland'),
  ('Casino Lugano', 'seed', 'Lugano', '', 'Switzerland'),
  ('Casino Bern', 'seed', 'Bern', '', 'Switzerland'),
  ('Casino Baden', 'seed', 'Baden', '', 'Switzerland'),
  ('Casino Vienna', 'seed', 'Vienna', '', 'Austria'),
  ('Casino Salzburg', 'seed', 'Salzburg', '', 'Austria'),
  ('Casino Innsbruck', 'seed', 'Innsbruck', '', 'Austria'),
  ('Casino Graz', 'seed', 'Graz', '', 'Austria')
on conflict (lower(name)) do nothing;

-- Australian casinos
insert into public.casinos (name, source, city, state, country)
values
  ('Crown Melbourne', 'seed', 'Southbank', 'Victoria', 'Australia'),
  ('The Star Sydney', 'seed', 'Sydney', 'New South Wales', 'Australia'),
  ('Crown Sydney', 'seed', 'Sydney', 'New South Wales', 'Australia'),
  ('Crown Perth', 'seed', 'Burswood', 'Western Australia', 'Australia'),
  ('The Star Gold Coast', 'seed', 'Broadbeach', 'Queensland', 'Australia'),
  ('The Star Brisbane', 'seed', 'Brisbane', 'Queensland', 'Australia'),
  ('Treasury Casino', 'seed', 'Brisbane', 'Queensland', 'Australia'),
  ('The Reef Hotel Casino', 'seed', 'Cairns', 'Queensland', 'Australia'),
  ('The Ville Resort-Casino', 'seed', 'Townsville', 'Queensland', 'Australia'),
  ('SkyCity Adelaide', 'seed', 'Adelaide', 'South Australia', 'Australia'),
  ('Casino Canberra', 'seed', 'Canberra', 'Australian Capital Territory', 'Australia'),
  ('Mindil Beach Casino Resort', 'seed', 'Darwin', 'Northern Territory', 'Australia'),
  ('Lasseters Hotel Casino', 'seed', 'Alice Springs', 'Northern Territory', 'Australia'),
  ('Crown Towers Melbourne', 'seed', 'Southbank', 'Victoria', 'Australia')
on conflict (lower(name)) do nothing;

-- Asian casinos
insert into public.casinos (name, source, city, state, country)
values
  ('The Venetian Macao', 'seed', 'Macau', '', 'Macau'),
  ('Wynn Palace', 'seed', 'Macau', '', 'Macau'),
  ('MGM Cotai', 'seed', 'Macau', '', 'Macau'),
  ('City of Dreams', 'seed', 'Macau', '', 'Macau'),
  ('Galaxy Macau', 'seed', 'Macau', '', 'Macau'),
  ('Sands Cotai Central', 'seed', 'Macau', '', 'Macau'),
  ('Wynn Macau', 'seed', 'Macau', '', 'Macau'),
  ('Sands Macao', 'seed', 'Macau', '', 'Macau'),
  ('MGM Macau', 'seed', 'Macau', '', 'Macau'),
  ('Grand Lisboa', 'seed', 'Macau', '', 'Macau'),
  ('Marina Bay Sands', 'seed', 'Singapore', '', 'Singapore'),
  ('Resorts World Sentosa', 'seed', 'Singapore', '', 'Singapore'),
  ('Solaire Resort & Casino', 'seed', 'Manila', '', 'Philippines'),
  ('City of Dreams Manila', 'seed', 'Manila', '', 'Philippines'),
  ('Okada Manila', 'seed', 'Manila', '', 'Philippines'),
  ('Resorts World Manila', 'seed', 'Manila', '', 'Philippines'),
  ('Hard Rock Hotel Casino Manila', 'seed', 'Manila', '', 'Philippines'),
  ('Jeju Shinhwa World', 'seed', 'Jeju', '', 'South Korea'),
  ('Paradise City', 'seed', 'Incheon', '', 'South Korea'),
  ('Grand Walkerhill Casino', 'seed', 'Seoul', '', 'South Korea'),
  ('NagaWorld', 'seed', 'Phnom Penh', '', 'Cambodia'),
  ('Naga2', 'seed', 'Phnom Penh', '', 'Cambodia'),
  ('Star Vegas', 'seed', 'Poipet', '', 'Cambodia')
on conflict (lower(name)) do nothing;
