-- Seed US casino names from curated list
-- Safe to re-run (ON CONFLICT DO NOTHING)

insert into public.casinos (name, source)
values
  ('Bellagio', 'seed'),
  ('Caesars Palace', 'seed'),
  ('MGM Grand', 'seed'),
  ('The Venetian', 'seed'),
  ('Wynn Las Vegas', 'seed'),
  ('Encore at Wynn', 'seed'),
  ('Aria Resort & Casino', 'seed'),
  ('The Cosmopolitan', 'seed'),
  ('Resorts World Las Vegas', 'seed'),
  ('Planet Hollywood', 'seed'),
  ('Flamingo Las Vegas', 'seed'),
  ('Paris Las Vegas', 'seed'),
  ('Treasure Island', 'seed'),
  ('Circus Circus', 'seed'),
  ('Golden Nugget', 'seed'),
  ('The LINQ', 'seed'),
  ('Park MGM', 'seed'),
  ('New York-New York', 'seed'),
  ('Excalibur', 'seed'),
  ('Luxor', 'seed'),
  ('Mandalay Bay', 'seed'),
  ('WinStar World Casino', 'seed'),
  ('Hard Rock Casino', 'seed'),
  ('Choctaw Casino & Resort', 'seed'),
  ('Cherokee Casino', 'seed'),
  ('Pechanga Resort Casino', 'seed'),
  ('Yaamava'' Resort & Casino', 'seed'),
  ('Thunder Valley Casino Resort', 'seed'),
  ('Morongo Casino Resort & Spa', 'seed'),
  ('San Manuel Casino', 'seed'),
  ('Foxwoods Resort Casino', 'seed'),
  ('Mohegan Sun', 'seed'),
  ('Borgata Hotel Casino & Spa', 'seed'),
  ('Hard Rock Hotel & Casino', 'seed'),
  ('Ocean Casino Resort', 'seed'),
  ('Seminole Hard Rock Hotel & Casino', 'seed'),
  ('Seminole Hard Rock Hotel & Casino', 'seed'),
  ('Beau Rivage Resort & Casino', 'seed'),
  ('Golden Nugget', 'seed'),
  ('Parx Casino', 'seed'),
  ('Wind Creek Bethlehem', 'seed'),
  ('Rivers Casino', 'seed'),
  ('MGM National Harbor', 'seed'),
  ('Live! Casino & Hotel', 'seed'),
  ('Horseshoe Casino', 'seed'),
  ('Ameristar Casino', 'seed'),
  ('Turning Stone Resort Casino', 'seed'),
  ('Hard Rock Casino', 'seed'),
  ('Riverwind Casino', 'seed'),
  ('Kickapoo Casino', 'seed'),
  ('Comanche Nation Casino', 'seed'),
  ('Chickasaw Casino', 'seed'),
  ('Gold River Casino', 'seed'),
  ('7 Clans First Council Casino', 'seed'),
  ('Apache Casino Hotel', 'seed'),
  ('Mystic Lake Casino', 'seed'),
  ('Canterbury Park', 'seed'),
  ('Treasure Island Casino', 'seed'),
  ('Jackpot Junction Casino', 'seed'),
  ('Prairie Edge Casino', 'seed'),
  ('Deadwood Mountain Grand', 'seed'),
  ('Four Bears Casino', 'seed'),
  ('Spirit Lake Casino', 'seed'),
  ('Tulalip Resort Casino', 'seed'),
  ('Muckleshoot Casino Resort', 'seed'),
  ('Snoqualmie Casino', 'seed'),
  ('Little Creek Casino Resort', 'seed'),
  ('Harrah''s Cherokee Casino Resort', 'seed'),
  ('Coushatta Casino Resort', 'seed'),
  ('L''Auberge Casino Resort', 'seed'),
  ('Margaritaville Resort Casino', 'seed'),
  ('Delta Downs Casino', 'seed'),
  ('Soaring Eagle Casino & Resort', 'seed'),
  ('FireKeepers Casino', 'seed'),
  ('Gun Lake Casino', 'seed'),
  ('Potawatomi Casino Hotel', 'seed'),
  ('Ho-Chunk Casino', 'seed'),
  ('Oneida Casino', 'seed'),
  ('Isle Casino Waterloo', 'seed'),
  ('Rivers Casino', 'seed'),
  ('Ameristar Casino', 'seed'),
  ('Horseshoe Council Bluffs', 'seed'),
  ('Argosy Casino', 'seed'),
  ('Hollywood Casino', 'seed'),
  ('Rivers Casino', 'seed'),
  ('Blue Chip Casino', 'seed'),
  ('Belterra Casino', 'seed'),
  ('French Lick Resort', 'seed'),
  ('Rising Sun Casino', 'seed'),
  ('Mountaineer Casino', 'seed'),
  ('Hollywood Casino', 'seed'),
  ('Hard Rock Casino', 'seed'),
  ('Jack Cleveland Casino', 'seed'),
  ('MGM Northfield Park', 'seed'),
  ('Presque Isle Downs & Casino', 'seed'),
  ('Harrah''s Philadelphia', 'seed'),
  ('Live! Casino Pittsburgh', 'seed'),
  ('Ocean Downs Casino', 'seed'),
  ('Wind Creek Atmore', 'seed'),
  ('Wind Creek Montgomery', 'seed'),
  ('Agua Caliente Casino', 'seed'),
  ('Talking Stick Resort', 'seed'),
  ('Casino Arizona', 'seed'),
  ('Harrah''s Ak-Chin Casino', 'seed'),
  ('Desert Diamond Casino', 'seed'),
  ('Casino Del Sol', 'seed'),
  ('Barona Resort & Casino', 'seed'),
  ('Viejas Casino', 'seed'),
  ('Jamul Casino', 'seed'),
  ('Sycuan Casino Resort', 'seed'),
  ('Pala Casino Spa Resort', 'seed')
on conflict (lower(name)) do nothing;
