/**
 * Bundled cashtag rows for instant local typeahead before / without `symbol_universe`.
 * Keep crypto tickers in sync with `marketCashtagCrypto.ts` / migration seed.
 */

import { withCashtagRowLogo } from './marketCashtagLogos.js'

const CRYPTO_SEED = [
  ['BTC', 'bitcoin', 'Bitcoin'],
  ['ETH', 'ethereum', 'Ethereum'],
  ['SOL', 'solana', 'Solana'],
  ['DOGE', 'dogecoin', 'Dogecoin'],
  ['XRP', 'ripple', 'XRP'],
  ['ADA', 'cardano', 'Cardano'],
  ['AVAX', 'avalanche-2', 'Avalanche'],
  ['LINK', 'chainlink', 'Chainlink'],
  ['BNB', 'binancecoin', 'BNB'],
  ['LTC', 'litecoin', 'Litecoin'],
  ['DOT', 'polkadot', 'Polkadot'],
  ['MATIC', 'matic-network', 'Polygon'],
  ['SHIB', 'shiba-inu', 'Shiba Inu'],
  ['UNI', 'uniswap', 'Uniswap'],
  ['ATOM', 'cosmos', 'Cosmos'],
  ['BCH', 'bitcoin-cash', 'Bitcoin Cash'],
  ['XLM', 'stellar', 'Stellar'],
  ['ETC', 'ethereum-classic', 'Ethereum Classic'],
  ['FIL', 'filecoin', 'Filecoin'],
  ['NEAR', 'near', 'NEAR Protocol'],
  ['APT', 'aptos', 'Aptos'],
  ['ARB', 'arbitrum', 'Arbitrum'],
  ['OP', 'optimism', 'Optimism'],
  ['PEPE', 'pepe', 'Pepe'],
  ['WIF', 'dogwifcoin', 'dogwifhat'],
  ['BONK', 'bonk', 'Bonk'],
  ['HBAR', 'hedera-hashgraph', 'Hedera'],
  ['ICP', 'internet-computer', 'Internet Computer'],
  ['VET', 'vechain', 'VeChain'],
  ['ALGO', 'algorand', 'Algorand'],
  ['AAVE', 'aave', 'Aave'],
  ['MKR', 'maker', 'Maker'],
  ['CRO', 'crypto-com-chain', 'Cronos'],
  ['STX', 'blockstack', 'Stacks'],
  ['INJ', 'injective-protocol', 'Injective'],
  ['RUNE', 'thorchain', 'THORChain'],
  ['SEI', 'sei-network', 'Sei'],
  ['TIA', 'celestia', 'Celestia'],
  ['SUI', 'sui', 'Sui'],
  ['TAO', 'bittensor', 'Bittensor'],
  ['FET', 'fetch-ai', 'Fetch.ai'],
  ['RENDER', 'render-token', 'Render'],
  ['WLD', 'worldcoin-wld', 'Worldcoin'],
  ['TRX', 'tron', 'TRON'],
]

const STOCK_SEED = [
  ['AAPL', 'Apple Inc'],
  ['MSFT', 'Microsoft Corporation'],
  ['GOOGL', 'Alphabet Inc Class A'],
  ['GOOG', 'Alphabet Inc Class C'],
  ['AMZN', 'Amazon.com Inc'],
  ['NVDA', 'NVIDIA Corporation'],
  ['META', 'Meta Platforms Inc'],
  ['TSLA', 'Tesla Inc'],
  ['BRK.B', 'Berkshire Hathaway Inc Class B'],
  ['JPM', 'JPMorgan Chase & Co'],
  ['V', 'Visa Inc'],
  ['UNH', 'UnitedHealth Group Inc'],
  ['XOM', 'Exxon Mobil Corporation'],
  ['JNJ', 'Johnson & Johnson'],
  ['WMT', 'Walmart Inc'],
  ['MA', 'Mastercard Inc'],
  ['HD', 'Home Depot Inc'],
  ['PG', 'Procter & Gamble Co'],
  ['AVGO', 'Broadcom Inc'],
  ['KO', 'Coca-Cola Co'],
  ['PEP', 'PepsiCo Inc'],
  ['COST', 'Costco Wholesale Corp'],
  ['AMD', 'Advanced Micro Devices Inc'],
  ['INTC', 'Intel Corporation'],
  ['CRM', 'Salesforce Inc'],
  ['NFLX', 'Netflix Inc'],
  ['DIS', 'Walt Disney Co'],
  ['BA', 'Boeing Co'],
  ['GS', 'Goldman Sachs Group Inc'],
  ['BAC', 'Bank of America Corp'],
  ['WFC', 'Wells Fargo & Co'],
  ['PYPL', 'PayPal Holdings Inc'],
  ['PLTR', 'Palantir Technologies Inc'],
  ['GME', 'GameStop Corp'],
  ['IPI', 'Intrepid Potash Inc'],
  ['LINK', 'Interlink Electronics Inc'],
  ['COIN', 'Coinbase Global Inc'],
  ['HOOD', 'Robinhood Markets Inc'],
  ['MSTR', 'MicroStrategy Inc'],
  ['SQ', 'Block Inc'],
  ['SHOP', 'Shopify Inc'],
  ['UBER', 'Uber Technologies Inc'],
  ['ABNB', 'Airbnb Inc'],
  ['SMCI', 'Super Micro Computer Inc'],
  ['ARM', 'Arm Holdings PLC'],
  ['RIVN', 'Rivian Automotive Inc'],
  ['F', 'Ford Motor Co'],
  ['GM', 'General Motors Co'],
]

/** @returns {object[]} */
export function getLoungeCashtagSymbolSeedRows() {
  const crypto = CRYPTO_SEED.map(([display, coin_id, name]) => ({
    symbol: `BINANCE:${display}USDT`,
    display_symbol: display,
    asset_class: 'crypto',
    name,
    exchange: 'Crypto',
    coin_id,
  }))
  const stocks = STOCK_SEED.map(([display, name]) => ({
    symbol: display,
    display_symbol: display,
    asset_class: 'stock',
    name,
    exchange: 'US',
  }))
  return [...crypto, ...stocks].map(withCashtagRowLogo)
}
