/**
 * Desolator "All AP References" v1.14 gaps — 10 slugs missing on test (2026-06-08).
 * Synthesized from PDF prose only (Ryan voice, no source attribution).
 */

/** @type {Array<{ machine: Record<string, unknown>, guide: Record<string, unknown> }>} */
export const DESOLATOR_GAP_PAYLOADS = [
  {
    machine: {
      slug: 'barnyard-poker',
      name: 'Barnyard Poker',
      manufacturer: 'IGT',
      type: 'Multiplier Video Poker',
      difficulty: 'Beginner',
      popularity: 'Uncommon',
      nerf_risk: 'Low',
      has_calculator: false,
      calculator_slug: null,
      volatility_index: 'Low-Medium',
      popularity_summary: '3-line IGT VP; exploding golden farm animals; big multiplier tags.',
      release_year: null,
    },
    guide: {
      title: 'Barnyard Poker',
      published: true,
      card_ev_threshold: 'Active multiplier tags (30x is the big one)',
      when_to_play: `**Primary play:** any **active multiplier** left on the **3-line** bank ... **30x** tags are the obvious sit.

**Quick check:** multiplier rail lit on the game/denom you are scouting. Even mid tags are worth a short run when someone else already paid for the feature bet.`,
      when_to_stop: `Stop when the multiplier stack you sat for **clears** ... usually **1–10 hands**.`,
      how_to_check: `Open each **Barnyard Poker** game and denom. Read the multiplier display for active tags. Cycle through all bets/denoms when a cabinet stacks multiple levels.`,
      risk_bankroll: `**10 units**`,
      risk_summary: `Weird **3-line-only** IGT VP ... easy to spot, easy to hop. Few players know the check so positive states linger.`,
      risk_bullets: [],
      where_to_find: '',
      skins_markdown: `**Barnyard Poker** only ... no separate pay-table skins on the same cabinet theme.`,
      gameplay_mechanics: `**Barnyard Poker** (IGT) is a **3-hand video poker** game with a farm-animal theme. Betting the **feature tier** turns on **multiplier mode** on winning hands. Multipliers apply to the next draw on that line.`,
    },
  },
  {
    machine: {
      slug: 'fortune-x-poker',
      name: 'Fortune X Poker',
      manufacturer: 'IGT',
      type: 'Multiplier Video Poker',
      difficulty: 'Intermediate',
      popularity: 'Uncommon',
      nerf_risk: 'Low',
      has_calculator: false,
      calculator_slug: null,
      volatility_index: 'Low',
      popularity_summary: 'Bottom-right multiplier string; optional use after the deal.',
      release_year: null,
    },
    guide: {
      title: 'Fortune X Poker',
      published: true,
      card_ev_threshold: 'Any active multiplier string (bottom-right)',
      when_to_play: `**Primary play:** any **active multiplier string** showing **bottom-right** on the game/denom you are scouting.

After the deal you **choose** whether to apply the multiplier. Use it when the hand's expected return beats the **pay-table baseline** in the corner chart ... most of the time the pay table is enough; tight spots need a hand analyzer or a educated guess.`,
      when_to_stop: `Stop when the multiplier string you sat for **expires** ... usually **1–4 hands**.`,
      how_to_check: `Check the **bottom-right multiplier string** on each game and denom. Cycle through all bets/denoms on multi-level cabinets.`,
      risk_bankroll: `**10 units**`,
      risk_summary: `Optional multiplier use adds a decision point mid-hand ... do not auto-apply on every deal.`,
      risk_bullets: [],
      where_to_find: '',
      skins_markdown: `Standard IGT pay-table variants on the same **Fortune X** shell ... same bottom-right string scout on every game.`,
      gameplay_mechanics: `**Fortune X Poker** (IGT) runs **multi-hand video poker** (**1–4 hands** common). A **multiplier string** displays bottom-right when someone left value in play. After the deal, the player decides whether to **commit the multiplier** to that hand.`,
    },
  },
  {
    machine: {
      slug: 'moving-multipliers-poker',
      name: 'Moving Multipliers Poker',
      manufacturer: 'IGT',
      type: 'Multiplier Video Poker',
      difficulty: 'Beginner',
      popularity: 'Common',
      nerf_risk: 'Low',
      has_calculator: false,
      calculator_slug: null,
      volatility_index: 'Low-Medium',
      popularity_summary: 'Consistent IGT VP; multipliers common; rarely leaves 700% tags.',
      release_year: null,
    },
    guide: {
      title: 'Moving Multipliers Poker',
      published: true,
      card_ev_threshold: 'Active moving multipliers on screen',
      when_to_play: `**Primary play:** any **active multiplier** on the game/denom you are scouting.

This is one of the more **consistent** IGT multiplier VP games ... positive states show up often and you usually get **multiple shots** at a high tag without the absurd leftover stacks **Ultimate X** sometimes leaves.`,
      when_to_stop: `Stop when the multiplier(s) you sat for **clear** ... usually **1–9 hands**.`,
      how_to_check: `Read the **moving multiplier** display on each game and denom. Cycle through all bets/denoms on stacked cabinets.`,
      risk_bankroll: `**15 units**`,
      risk_summary: `Hard to find **700%** leftovers like **Ultimate X**, but far easier to find **playable** tags in normal rotation.`,
      risk_bullets: [],
      where_to_find: '',
      skins_markdown: `**Jacks or Better**, **Bonus Poker**, **Deuces Wild**, and other IGT pay tables on the same **Moving Multipliers** cabinet.`,
      gameplay_mechanics: `**Moving Multipliers Poker** (IGT) runs standard **multi-line video poker** with **moving multiplier** indicators that persist across hands until they expire or pay off. Multipliers shift position on screen as the feature progresses.`,
    },
  },
  {
    machine: {
      slug: 'multipliers-rising-poker',
      name: 'Multipliers Rising Poker',
      manufacturer: 'IGT',
      type: 'Multiplier Video Poker',
      difficulty: 'Beginner',
      popularity: 'Common',
      nerf_risk: 'Low',
      has_calculator: false,
      calculator_slug: null,
      volatility_index: 'Low',
      popularity_summary: 'Simple VP check; re-triggers often; no chart math.',
      release_year: null,
    },
    guide: {
      title: 'Multipliers Rising Poker',
      published: true,
      card_ev_threshold: 'Active rising multipliers on screen',
      when_to_play: `**Primary play:** any **active rising multiplier** on the game/denom you are scouting.

**Simple read:** if multipliers are lit, sit. Re-triggers happen **regardless of card wins** more often than **Bonus Streak**-style games ... that is why this one prints.`,
      when_to_stop: `Stop when multipliers **clear** or drop to a non-positive state ... usually **1–3 hands**, longer only if it re-triggers hot.`,
      how_to_check: `Read the **rising multiplier** meter on each game and denom. Cycle through all bets/denoms.`,
      risk_bankroll: `**10 units**`,
      risk_summary: `Re-triggers can extend a sit ... still a **very short** run by design.`,
      risk_bullets: [],
      where_to_find: '',
      skins_markdown: `IGT pay-table variants on the same **Multipliers Rising** shell.`,
      gameplay_mechanics: `**Multipliers Rising Poker** (IGT) applies **rising multipliers** across multi-hand video poker. Multipliers can **re-trigger** on subsequent deals independent of whether the prior hand was a winner.`,
    },
  },
  {
    machine: {
      slug: 'multi-streak-poker',
      name: 'Multi-Streak Poker',
      manufacturer: 'IGT',
      type: 'Multiplier Video Poker',
      difficulty: 'Intermediate',
      popularity: 'Uncommon',
      nerf_risk: 'Low',
      has_calculator: false,
      calculator_slug: null,
      volatility_index: 'Low-Medium',
      popularity_summary: 'Precursor to Bonus Streak; halve bet and keep multipliers.',
      release_year: null,
    },
    guide: {
      title: 'Multi-Streak Poker',
      published: true,
      card_ev_threshold: 'Active multi-hand multiplier streak',
      when_to_play: `**Primary play:** any **active multiplier streak** on the game/denom you are scouting.

Multipliers apply to **all lines** for **multiple upcoming hands** based on the dealt hand. You can also **cut the bet in half** and still consume the streak **without** a re-trigger chance ... that combo makes this technically cleaner than [Ultimate X Bonus Streak Poker](guide:ultimate-x-bonus-streak-poker) on many tags.`,
      when_to_stop: `Stop when the streak you sat for **finishes** ... usually **1–3 hands**.`,
      how_to_check: `Read the **streak multiplier** stack on each game and denom. Cycle through all bets/denoms.`,
      risk_bankroll: `**10 units**`,
      risk_summary: `Halving the bet burns the streak without re-trigger ... know which mode you are buying before you draw.`,
      risk_bullets: [],
      where_to_find: '',
      skins_markdown: `Precursor cabinet to [Ultimate X Bonus Streak Poker](guide:ultimate-x-bonus-streak-poker). IGT pay-table variants on the same **Multi-Streak** shell.`,
      gameplay_mechanics: `**Multi-Streak Poker** (IGT) seeds **multi-hand multiplier streaks** from dealt hands. The multiplier applies to **every line** in play for the streak length. **Half-bet** mode lets you play off tags at reduced cost without re-triggering.`,
    },
  },
  {
    machine: {
      slug: 'pay-upgrade',
      name: 'Pay Upgrade',
      manufacturer: 'Various',
      type: 'Persistent State',
      difficulty: 'Beginner',
      popularity: 'Rare',
      nerf_risk: 'High',
      has_calculator: false,
      calculator_slug: null,
      volatility_index: 'Low',
      popularity_summary: 'Green background = 2x pay; scout bet × line matrix per denom.',
      release_year: null,
    },
    guide: {
      title: 'Pay Upgrade',
      published: true,
      card_ev_threshold: 'Green background on any bet/line state',
      when_to_play: `**Primary play:** any **green background** on the bet/line grid ... that is **2x pay** where all wins double and spin results skew slightly better.

Scout **quarters** from **1 bet / 1 line** through **18 bet / 9 lines**, then repeat on **50¢**, **$1**, and **$2**. Progressive qualifies at **max bet (18)** per denom. Some **$1-only** installs use **9 / 18 / 27** bet steps instead.`,
      when_to_stop: `Stop after **1–3 spins** unless it **re-triggers** green ... by design this is an ultra-short sit.`,
      how_to_check: `Set each denom, press **bet down** to walk **1–18 bet × 1–9 lines** (or **9/18/27** on $1-only). **Green background = sit**. Insert a **checker ticket** when credits are required to change bet/line. Cycle through all bets/denoms.`,
      risk_bankroll: `**20 units**`,
      risk_summary: `Not the **Pay Upgrade symbol** on **Blazin' Diamond** cabinets ... this is the standalone **persistent green-state** scout game.`,
      risk_bullets: [],
      where_to_find: '',
      skins_markdown: `**Pay Upgrade** standalone persistent-state slot ... separate from Blazin' Diamond-style **Pay Upgrade symbols**.`,
      gameplay_mechanics: `**Pay Upgrade** is a **persistent-state slot** where the UI background turns **green** in a **2x pay** configuration. Wins double while the state is active. Bet/line combinations are stored **per denomination** until consumed or cleared.`,
    },
  },
  {
    machine: {
      slug: 'pick-a-multiplier-poker',
      name: 'Pick a Multiplier Poker',
      manufacturer: 'IGT',
      type: 'Multiplier Video Poker',
      difficulty: 'Beginner',
      popularity: 'Common',
      nerf_risk: 'Low',
      has_calculator: false,
      calculator_slug: null,
      volatility_index: 'Low',
      popularity_summary: 'Fastest VP check; double bet buys multiplier pick.',
      release_year: null,
    },
    guide: {
      title: 'Pick a Multiplier Poker',
      published: true,
      card_ev_threshold: 'Any active multiplier (6x ≈ +EV)',
      when_to_play: `**Primary play:** any **active multiplier** on the game/denom you are scouting.

**Quick math:** feature costs **double bet**, so a **6x** showing is roughly **300% RTP** minus the tiny pay-table edge ... that is why this is the fastest VP check on the floor.`,
      when_to_stop: `Stop after **one hand** unless it **re-triggers** another multiplier pick.`,
      how_to_check: `Read the **multiplier pick** display on each game and denom. Cycle through all bets/denoms.`,
      risk_bankroll: `**5 units**`,
      risk_summary: `One-hand default ... fastest VP check in rotation when you know the read.`,
      risk_bullets: [],
      where_to_find: '',
      skins_markdown: `IGT pay-table variants on the same **Pick a Multiplier** shell.`,
      gameplay_mechanics: `**Pick a Multiplier Poker** (IGT) runs **single-hand video poker** with an optional **multiplier pick** bought at **double the standard bet**. The chosen multiplier applies to the current hand outcome.`,
    },
  },
  {
    machine: {
      slug: 'quick-hit-platinum',
      name: 'Quick Hit Platinum',
      manufacturer: 'Bally / Light & Wonder',
      type: 'Must-Hit-By Progressive',
      difficulty: 'Advanced',
      popularity: 'Common',
      nerf_risk: 'Low',
      has_calculator: false,
      calculator_slug: null,
      volatility_index: 'Medium',
      popularity_summary: 'Minor chase near $900; frequent bonuses; not Ultra Pays.',
      release_year: null,
    },
    guide: {
      title: 'Quick Hit Platinum',
      published: true,
      card_ev_threshold: 'Minor near $900 at min bet (10c × $7.50)',
      when_to_play: `**Primary play:** **minor progressive** in the **high-$800s / ~$900** band at a **good-RTP casino** (~**$895** floor at tighter joints).

**Bet:** **10¢ denom min bet ($7.50)** ... do **not** max-bet this chase. Bonuses hit often so volatility stays manageable at min bet.

Separate game from [Quick Hit Ultra Pays](guide:quick-hit-ultra-pays) ... this is the **platinum-bar minor** chase cabinet.`,
      when_to_stop: `Stop when the **minor hits** or you clear a failed chase. **Do not** raise bet near the target ... past-target behavior pays through bonus animation, not a max-bet edge.`,
      how_to_check: `Read the **minor progressive** on the glass. Cycle through all bets/denoms if the cabinet stacks levels ... hunt is **min bet dimes** first.`,
      risk_bankroll: `**500 units**`,
      risk_summary: `Long minor chase ... hundreds of spins typical. **Nickels ($3.75)** smooth variance but slow the meter.`,
      risk_bullets: [],
      where_to_find: '',
      skins_markdown: `**Quick Hit Platinum** only ... cousin ladder game is [Quick Hit Ultra Pays](guide:quick-hit-ultra-pays), not the same hunt.`,
      gameplay_mechanics: `**Quick Hit Platinum** (Bally / Light & Wonder) accrues a **minor progressive** (~**$0.09** per **$7.50** wager toward the minor). **Platinum bar** bonuses fire frequently. The minor can hit in normal bonus flow or roll past the target to an internal safety number with a different animation.`,
    },
  },
  {
    machine: {
      slug: 'super-hot-roll-poker',
      name: 'Super Hot Roll Poker',
      manufacturer: 'IGT',
      type: 'Multiplier Video Poker',
      difficulty: 'Intermediate',
      popularity: 'Uncommon',
      nerf_risk: 'Low',
      has_calculator: false,
      calculator_slug: null,
      volatility_index: 'Low',
      popularity_summary: 'Tedious scout; positive states linger; 1-hand default.',
      release_year: null,
    },
    guide: {
      title: 'Super Hot Roll Poker',
      published: true,
      card_ev_threshold: 'Active Hot Roll multiplier on screen',
      when_to_play: `**Primary play:** any **positive Hot Roll multiplier state** on the game/denom you are scouting.

Tedious to check, but **positive states linger** because few APs know the read ... worth learning the scout once.`,
      when_to_stop: `Stop after **one hand** unless it **re-triggers** into another positive state.`,
      how_to_check: `Work through each **Super Hot Roll** game and denom with the Hot Roll multiplier panel read. Cycle through all bets/denoms ... insert a **checker ticket** when the install requires credits to cycle.`,
      risk_bankroll: `**5 units**`,
      risk_summary: `Scout is slower than **Pick a Multiplier** ... competition is lighter for the same reason.`,
      risk_bullets: [],
      where_to_find: '',
      skins_markdown: `IGT pay-table variants on the same **Super Hot Roll** shell.`,
      gameplay_mechanics: `**Super Hot Roll Poker** (IGT) wraps standard **video poker** with a **Hot Roll multiplier** feature that can **re-trigger** on the next hand when conditions align.`,
    },
  },
  {
    machine: {
      slug: 'ultimate-x-bonus-streak-poker',
      name: 'Ultimate X Bonus Streak Poker',
      manufacturer: 'IGT',
      type: 'Multiplier Video Poker',
      difficulty: 'Advanced',
      popularity: 'Common',
      nerf_risk: 'Low',
      has_calculator: false,
      calculator_slug: null,
      volatility_index: 'Medium',
      popularity_summary: 'UX without half-bet; stacked multiplier layers; line-count math.',
      release_year: null,
    },
    guide: {
      title: 'Ultimate X Bonus Streak Poker',
      published: true,
      card_ev_threshold: 'Stacked multiplier total ≥ chart threshold for hand count',
      when_to_play: `**Primary play:** when **stacked multiplier layers** on screen total **at or above** the chart threshold for your **hand count** (**10-, 5-, or 3-hand** games use different rows).

**No half-bet escape** like classic [Ultimate X Poker](guide:ultimate-x-poker) ... you pay full multiplier bet or pass.

**Layer math:** **1st layer** = next-hand multipliers; **2nd layer** = next hand **plus** the hand after. Empty lines count as implied **1x** in each layer you are stacking. Example on **5-hand**: tags **4x, 4x, 2x**, two blanks → **4+4+2+1+1 = 12x** ... sit when the chart says **11+** for that line count.

Precursor cousin: [Multi-Streak Poker](guide:multi-streak-poker) (half-bet still works there).`,
      when_to_stop: `Stop when multiplier layers **clear** or drop below threshold ... usually **1–10 hands**, longer only on **re-triggers**.`,
      how_to_check: `Read **both multiplier layers** (when present) on each game, denom, and **hand-count** setting. Sum tags plus implied **1x** blanks per layer, compare to the chart row. Cycle through all bets/denoms.`,
      risk_bankroll: `**15 units**`,
      risk_summary: `Higher variance than classic **Ultimate X** because **half-bet** is gone ... mis-read line count or layer stacking and you are paying full premium for nothing.`,
      risk_bullets: [],
      where_to_find: '',
      skins_markdown: `Successor to [Multi-Streak Poker](guide:multi-streak-poker). Classic scavenger cousin: [Ultimate X Poker](guide:ultimate-x-poker). IGT pay-table variants on the same **Bonus Streak** shell.`,
      gameplay_mechanics: `**Ultimate X Bonus Streak Poker** (IGT) runs **3-, 5-, and 10-hand** video poker with **two stacked multiplier layers** per line. Multipliers apply across upcoming hands until consumed. **Re-triggers** extend the streak when new winning hands seed fresh tags.`,
    },
  },
]
